### ISSUE TITLE
Can't insert into table

### ISSUE THREAD

**Issue by snake302** [Infinidat/infi.clickhouse_orm#144]
Hi there,

I have spend 3 hours with your library, but everything ends when I am trying to insert something into DB:

> Traceback (most recent call last):
  File "/var/python/clickhouse.py", line 90, in <module>
    doubler()
  File "/var/python/clickhouse.py", line 83, in doubler
    appid])
  File "/usr/local/lib/python3.6/dist-packages/infi/clickhouse_orm/database.py", line 199, in insert
    if first_instance.is_read_only() or first_instance.is_system_model():
AttributeError: 'str' object has no attribute 'is_read_only'

**Comment by vladimirteddy** [comment]
How can you fix it ```AttributeError: 'str' object has no attribute 'is_read_only'```?
