### ISSUE TITLE
IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2

### ISSUE THREAD

**Issue by TvoroG** [Infinidat/infi.clickhouse_orm#32]
I've tried to build a develop version of project using `python 2.7` and failed.

Here is the steps to reproduce:
``` shell
git clone https://github.com/Infinidat/infi.clickhouse_orm.git
easy_install -U infi.projector
cd infi.clickhouse_orm
projector devenv build
```

Output of last command:
```
$ projector devenv build
Executing /nix/store/7z5xc3xlpzq6w694p9mnxdbdp0rsskvs-python-2.7.13/bin/buildout bootstrap
Executing buildout bootstrap
Executing bin/buildout buildout:develop= install setup.py __version__.py
Executing bin/buildout install development-scripts
zip_safe flag not set; analyzing archive contents...
emport.__init__: module references __path__

IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Beginning with IPython 6.0, Python 3.3 and above is required.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/master/README.rst

Python sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0) detected.


error: Setup script exited with 1
While:
  Installing development-scripts.
  Getting distribution for 'ipython'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/infi.recipe.console_scripts-0.4-py2.7.egg/infi/recipe/console_scripts/__init__.py", line 26, in install
    installed_files = super(Scripts, self).install()
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack

Traceback (most recent call last):
  File "/home/user/.virtualenvs/chorm_test2/bin/projector", line 11, in <module>
    load_entry_point('infi.projector==1.0.2', 'console_scripts', 'projector')()
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/scripts/__init__.py", line 10, in projector
    parse_commandline_arguments(argv)
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/commandline_parser/__init__.py", line 124, in parse_commandline_arguments
    if not any(selected_plugin.parse_commandline_arguments(arguments) for selected_plugin in selected_plugins):
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/commandline_parser/__init__.py", line 124, in <genexpr>
    if not any(selected_plugin.parse_commandline_arguments(arguments) for selected_plugin in selected_plugins):
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/plugins/__init__.py", line 27, in parse_commandline_arguments
    method()
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/plugins/builtins/devenv/__init__.py", line 215, in build
    self.create_scripts()
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/plugins/builtins/devenv/__init__.py", line 114, in create_scripts
    self.install_sections_by_recipe("infi.recipe.console_scripts")
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/plugins/builtins/devenv/__init__.py", line 89, in install_sections_by_recipe
    utils.execute_with_buildout("install {}".format(' '.join(sections_to_install)), stripped=stripped)
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/helper/utils/__init__.py", line 163, in execute_with_buildout
    execute_assert_success([buildout] + BUILDOUT_PARAMETERS + args, env=_env)
  File "/home/user/.virtualenvs/chorm_test2/lib/python2.7/site-packages/infi.projector-1.0.2-py2.7.egg/infi/projector/helper/utils/__init__.py", line 72, in execute_assert_success
    raise PrettyExecutionError(result)
infi.projector.helper.utils.PrettyExecutionError: Execution of ['bin/buildout', 'install', 'development-scripts'] failed!
result=1
stdout=Develop: '/home/user/programming/test/infi.clickhouse_orm/.'
Getting distribution for 'infi.recipe.console_scripts'.
Got infi.recipe.console-scripts 0.4.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
Getting distribution for 'z3c.recipe.scripts'.
Got z3c.recipe.scripts 1.0.1.
Getting distribution for 'infi.pyutils'.
Got infi.pyutils 1.1.3.
Getting distribution for 'emport'.
Got emport 1.2.0.
Getting distribution for 'mock'.

Installed /tmp/easy_install-AZWAS0/mock-2.0.0/.eggs/pbr-3.0.0-py2.7.egg
Got mock 2.0.0.
Getting distribution for 'Logbook>=0.11.0'.
Got Logbook 1.0.0.
Getting distribution for 'pbr>=0.11'.
Got pbr 3.0.0.
Getting distribution for 'funcsigs>=1'.
Got funcsigs 1.0.2.
Installing development-scripts.
Getting distribution for 'ipython'.
An error occurred when trying to install /home/user/programming/test/infi.clickhouse_orm/.cache/dist/ipython-6.0.0.tar.gz. Look above this message for any errors that were output by easy_install.

stderr=zip_safe flag not set; analyzing archive contents...
emport.__init__: module references __path__

IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Beginning with IPython 6.0, Python 3.3 and above is required.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/master/README.rst

Python sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0) detected.


error: Setup script exited with 1
While:
  Installing development-scripts.
  Getting distribution for 'ipython'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/infi.recipe.console_scripts-0.4-py2.7.egg/infi/recipe/console_scripts/__init__.py", line 26, in install
    installed_files = super(Scripts, self).install()
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/user/programming/test/infi.clickhouse_orm/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack

```

**Comment by ishirav** [comment]
OK, please try the following: 
edit the file buildout.cfg and change line 46 from:
```
eggs = ${project:name}
	ipython
	nose
```
to
```
eggs = ${project:name}
	ipython<6
	nose
```
Then run: `projector devenv build --clean`

**Comment by bitshark** [comment]
@ishirav I had the exact same problem with the latest release of infi.systray (on Windows 7 non-cygwin), which was resolved by changing buildout to ipython<6
