### ISSUE TITLE
Can't modify enum choices

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#47]
I try to add choices to fields.Enum8Field with migrations.AlterTable and get:
```
Traceback (most recent call last):
  File "/home/sergei/.pycharm_helpers/pycharm/django_manage.py", line 43, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python3.5/runpy.py", line 196, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sergei/cqapi/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sergei/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/sergei/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sergei/venv/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sergei/venv/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/sergei/cqapi/utils/management/commands/ch_migrate.py", line 60, in handle
    self._apply_migrations(p)
  File "/home/sergei/cqapi/utils/management/commands/ch_migrate.py", line 21, in _apply_migrations
    settings.CLICKHOUSE_DB.migrate(package_name)
  File "/home/sergei/venv/lib/python3.5/site-packages/infi.clickhouse_orm-0.7.2.post84-py3.5.egg/infi/clickhouse_orm/database.py", line 151, in migrate
    operation.apply(self)
  File "/home/sergei/venv/lib/python3.5/site-packages/infi.clickhouse_orm-0.7.2.post84-py3.5.egg/infi/clickhouse_orm/migrations.py", line 77, in apply
    assert model_field[0] == table_field[0], 'Model fields and table columns in disagreement'
AssertionError: Model fields and table columns in disagreement
```

**Comment by ishirav** [comment]
Can you list the model class definition, and also the output of DESCRIBE TABLE ?

**Comment by M1hacka** [comment]
Not really easy =) I've removed all methods to make the code smaller
```
# ConversationPart django model partial
class ConversationPart(CollapseDjangoModel):
    REPLY_USER = 'reply_user'
    REPLY_ADMIN = 'reply_admin'
    NOTE = 'note'
    TAG_ADDED = 'tag_added'
    TAG_DELETED = 'tag_deleted'
    ASSIGNED = 'assigned'
    CLOSED = 'closed'
    FINAL_CLOSED = 'final_closed'
    OPENED = 'opened'
    SERVICE = 'service'
    CHANNEL_CHANGED = 'channel_changed'
    CHANNEL_RESTORED = 'channel_restored'
    TYPE_CHOICES = (
        (REPLY_USER, 'Ответ от пользователя'),
        (REPLY_ADMIN, 'Ответ от админа'),
        (NOTE, 'Заметка'),
        (TAG_ADDED, 'Добавлен тег'),  # В body лежит тег
        (TAG_DELETED, 'Удален тег'),  # В body лежит тег
        (ASSIGNED, 'Диалог назначен'),  # В body лежит ID админа, которому назначен диалог
        (OPENED, 'Диалог открыт'),
        (SERVICE, 'Сервисное сообщение'),

        # Когда пользователь закрывает диалог - у него появляется CLOSED.
        # Когда проходит контрольное время на продолжение диалога - у него появляется FINAL_CLOSED
        (CLOSED, 'Диалог закрыт'),
        (FINAL_CLOSED, 'Вопрос решён'),

        # These 2 choices were added at last commit
        (CHANNEL_CHANGED, 'Изменен канал диалога'),
        (CHANNEL_RESTORED, 'Восстановлен канал диалога'),
    )

    USER2APP = 'u2a'
    APP2USER = 'a2u'
    DIRECTIONS = ((USER2APP, 'User -> app'), (APP2USER, 'App -> user'))

# Choice items are generated automatically, based on Django models constants
CHConversationPartDirection = IntEnum('Enum', [c[0] for c in ConversationPart.DIRECTIONS])
CHConversationPartType = IntEnum('Enum', [c[0] for c in ConversationPart.TYPE_CHOICES])

# ClickHouseBaseModel inherits models.Model from clickhouse-orm and doesn't contain any field attributes
class ClickHouseCollapseModel(ClickHouseBaseModel):
    """
    Adds operations for  engine CollapsingMergeTree
    https://clickhouse.yandex/reference_en.html#CollapsingMergeTree
    """
    # ClickHouse field name, containing sign for collapse operations
    clickhouse_sign_field = "sign"

    # Number of last inserted row. It is added automatically to each row on insert or update
    # It is used to get the last version of data, if it was not collapsed yet.
    _version = fields.UInt32Field(default=0)


class CHConversationPart(ClickHouseCollapseModel):
    id = fields.UInt64Field()
    created = fields.DateTimeField()
    created_date = fields.DateField(materialized='toDate(created)')

    first = fields.UInt8Field(default=0)
    conversation_id = fields.UInt64Field()

    part_group_id = fields.UInt64Field()

    inbound_email_id = fields.UInt64Field(default=0)
    body = fields.StringField()
    user_id = fields.UInt64Field(default=0)
    django_user_id = fields.UInt64Field(default=0)
    app_id = fields.UInt64Field()

    direction = fields.Enum8Field(CHConversationPartDirection)
    email_message_id = fields.StringField()
    sent_via = fields.StringField()
    type = fields.Enum8Field(CHConversationPartType)

    read = fields.UInt8Field(default=0)

    sign = fields.Int8Field(default=1)

    engine = engines.CollapsingMergeTree('created_date', ('id', 'app_id'), 'sign')

    # Not field service attributes
    django_model = ConversationPart
    auto_sync = 5
```

Here is DESCRIBE TABLE results:
[chconversationpart_describe.txt](https://github.com/Infinidat/infi.clickhouse_orm/files/1263471/chconversationpart_describe.txt)

**Comment by ishirav** [comment]
OK, I'm not sure whether the problem is with an enum field or with the created_date field - in the model it appears as the 3rd field, but in the table it appears last. Perhaps you can try running the migration under pdb to check which field causes the exception.

**Comment by M1hacka** [comment]
model_field[0] is created_date
table_field[0] is first

**Comment by M1hacka** [comment]
What is the purpose of this assert? May be it can be solved by using another model_fields format? dict by name, for instance.

**Comment by ishirav** [comment]
AlterTable attempts to keep the order of the columns in the model and the database the same. You can see that when adding a column, it uses ADD COLUMN x AFTER y. 
So when checking columns for changes, it expects to find them in the same positions.
I think that if you move created_date to the end of the model fields, the migration might work.
That said, it might be worth reconsidering whether the assertion is truly necessary.

**Comment by M1hacka** [comment]
While trying to solve this bug, I've found another one. If field has MATERIALIZED or ALIAS, _get_table_fields returns only type field which is `Date`, while field.get_sql(with_default=False) returns `Date MATERIALIZED toDate(created)`. I suppose, that it's better to compare field with default expression (or it won't be updated, if it is changed in the model).

**Comment by M1hacka** [comment]
Yes, I suppose moving it to the end will work. But it seems, there's a bug someware else, as I haven't modifyed anything in this model, except for Enum field choices. So the order of columns didn't changed. More than that, if I switch to another git branch with same column order in the model migrations pass successfully...

**Comment by M1hacka** [comment]
The bug is really not updating the model, but creating it:
```
from infi.clickhouse_orm.models import Model


class CHTest(Model):
    id = fields.Int64Field()
    created = fields.DateTimeField()
    created_date = fields.DateField(materialized='toDate(created)')

    first = fields.UInt8Field(default=0)
    sign = fields.UInt8Field(default=1)

    engine = engines.CollapsingMergeTree('created_date', ('id',), 'sign')

settings.CLICKHOUSE_DB.create_table(CHTest)
```

`DESC chtest`:
![image](https://user-images.githubusercontent.com/2315339/30378779-c821eee8-98ad-11e7-9394-674065671ea6.png)

So further alter migration failes, as created_date is standing last. I suppose, it's connected with its MATERIALIZED nature.

**Comment by M1hacka** [comment]
Hello. I'd like to try fixing this issue, but there are many pull requests now, that add sample migrations. In order to resolve less conflicts after bug is solved, I'd like to know, when the release is planned or what PRs will be inside (in order to merge them to my branch). Thanks.
