### ISSUE TITLE
select query fails, if query contains '$' symbol

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#56]
`list(db.select("SELECT value FROM $table WHERE key ='$utm_source'", model_class=CHEventProperty))`
raises Exception
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/sergei/venv36/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 157, in select
    query = self._substitute(query, model_class)
  File "/home/sergei/venv36/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 273, in _substitute
    query = Template(query).substitute(mapping)
  File "/usr/lib/python3.6/string.py", line 126, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python3.6/string.py", line 119, in convert
    return str(mapping[named])
KeyError: 'utm_source'
```

The problem is `database._substitute()` method which uses `Template(query).substitute(mapping)`. Template expects all keys mentioned in query being in mapping. Suppose, [safe_substitute()](https://docs.python.org/2/library/string.html#string.Template.safe_substitute) method should be used here.

**Comment by M1hacka** [comment]
Wrote test and submitted [pull request](https://github.com/Infinidat/infi.clickhouse_orm/pull/57)
