### ISSUE TITLE
test_engines.EnginesTestCase.test_merge_tree_with_sampling fails on Clickhouse 1.1.54370

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#64]
ClickHouse version: 1.1.54370
infi.clickhouse_orm: master
```
Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/sergei/infi.clickhouse_orm/tests/test_engines.py", line 35, in test_merge_tree_with_sampling
    self._create_and_insert(TestModel)
  File "/home/sergei/infi.clickhouse_orm/tests/test_engines.py", line 22, in _create_and_insert
    self.database.create_table(model_class)
  File "/home/sergei/infi.clickhouse_orm/src/infi/clickhouse_orm/database.py", line 80, in create_table
    self._send(model_class.create_table_sql(self.db_name))
  File "/home/sergei/infi.clickhouse_orm/src/infi/clickhouse_orm/database.py", line 253, in _send
    raise DatabaseException(r.text)
Exception: Code: 36, e.displayText() = DB::Exception: Sampling expression must be present in the primary key, e.what() = DB::Exception

-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:8123 "POST / HTTP/1.1" 200 None
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:8123 "POST /?database=test-db HTTP/1.1" 200 None
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:8123 "POST /?database=test-db HTTP/1.1" 500 None
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:8123 "POST /?database=test-db HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------
```
Is it a test bug (just add sampling expression to PK in test) or it's better to add python assertion? I may fix it along with developing [custom partitioning](https://clickhouse.yandex/docs/en/table_engines/custom_partitioning_key/).

**Comment by ishirav** [comment]
The test is already fixed in the develop branch.

**Comment by M1hacka** [comment]
ok
