### ISSUE TITLE
Raw sql query fails

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#66]
Hi
An error occures making raw sql query with infi.clickhouse_orm 0.9.8 and ClickHouse 1.1.54370
```Python
Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/sergei/cqapi/messages/tests/test_ch_models.py", line 1055, in test_get_stats_message
    stats = CHSendingsInteraction.get_stats(msg.app, start, start, group_range='hour', message=msg)
  File "/home/sergei/cqapi/messages/ch_models.py", line 1220, in get_stats
    start_date, end_date)
  File "/home/sergei/cqapi/messages/ch_models.py", line 1128, in _format_stat_result
    for item in ch_data:
  File "/home/sergei/infi.clickhouse_orm/src/infi/clickhouse_orm/database.py", line 166, in select
    model_class = model_class or ModelBase.create_ad_hoc_model(zip(field_names, field_types))
  File "/home/sergei/infi.clickhouse_orm/src/infi/clickhouse_orm/models.py", line 48, in create_ad_hoc_model
    attrs[name] = cls.create_ad_hoc_field(db_type)
  File "/home/sergei/infi.clickhouse_orm/src/infi/clickhouse_orm/models.py", line 75, in create_ad_hoc_field
    raise NotImplementedError('No field class for %s' % db_type)
NotImplementedError: No field class for DateTime('Asia/Yekaterinburg')
```

The reason is displayed here:
![image](https://user-images.githubusercontent.com/2315339/38869206-52ffa17c-4263-11e8-8d51-e8e782b40483.png)

It seems that TabSeparatedWithNamesAndTypes returns format description with timezone, which is not parsed well in (It is handled as simple field and add Field after brackets):

```Python
    @classmethod
    def create_ad_hoc_field(cls, db_type):
        import infi.clickhouse_orm.fields as orm_fields
        # Enums
        if db_type.startswith('Enum'):
            return orm_fields.BaseEnumField.create_ad_hoc_field(db_type)
        # Arrays
        if db_type.startswith('Array'):
            inner_field = cls.create_ad_hoc_field(db_type[6 : -1])
            return orm_fields.ArrayField(inner_field)
        # FixedString
        if db_type.startswith('FixedString'):
            length = int(db_type[12 : -1])
            return orm_fields.FixedStringField(length)
        # Nullable
        if db_type.startswith('Nullable'):
            inner_field = cls.create_ad_hoc_field(db_type[9 : -1])
            return orm_fields.NullableField(inner_field)
        # Simple fields
        name = db_type + 'Field'
        if not hasattr(orm_fields, name):
            raise NotImplementedError('No field class for %s' % db_type)
        return getattr(orm_fields, name)()
```

**Comment by ishirav** [comment]
So if I understand correctly, ClickHouse started returning the timezone for DateTime fields and the ORM doesn't expect it?

**Comment by M1hacka** [comment]
Yes

**Comment by M1hacka** [comment]
More info. It seems, that result is returned not for DateTimeField, but for results of toStartOfHour(dt) function

**Comment by M1hacka** [comment]
When is release planned?

**Comment by ishirav** [comment]
I'm hoping to release v1.0 next week.

**Comment by ishirav** [comment]
v1.0.0 was released.
