### ISSUE TITLE
Got an error while building package

### ISSUE THREAD

**Issue by kalombos** [Infinidat/infi.clickhouse_orm#75]
After ```projector devenv build``` command:

```
Executing /usr/bin/buildout bootstrap
Executing buildout bootstrap
Executing bin/buildout buildout:develop= install setup.py __version__.py
b'warning: no files found matching \'shootout.cfg\'\nWhile:\n  Installing.\n  Loading extensions.\n\nAn internal error occurred due to a bug in either zc.buildout or in a\nrecipe being used:\nTraceback (most recent call last):\n  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/zc.buildout-2.11.5-py3.5.egg/zc/buildout/buildout.py", line 2127, in main\n    getattr(buildout, command)(args)\n  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/zc.buildout-2.11.5-py3.5.egg/zc/buildout/buildout.py", line 638, in install\n    self._load_extensions()\n  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/zc.buildout-2.11.5-py3.5.egg/zc/buildout/buildout.py", line 1174, in _load_extensions\n    ep.load()(self)\n  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load\n    return self.resolve()\n  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve\n    module = __import__(self.module_name, fromlist=[\'__name__\'], level=0)\n  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/buildout.wheel-0.2.0-py3.5.egg/buildout/wheel/__init__.py", line 9, in <module>\n    import pip.pep425tags\nImportError: No module named \'pip.pep425tags\'\n'
Traceback (most recent call last):
  File "/home/kalombo/.virtualenvs/infi/bin/projector", line 11, in <module>
    load_entry_point('infi.projector==1.0.5', 'console_scripts', 'projector')()
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/scripts/__init__.py", line 10, in projector
    parse_commandline_arguments(argv)
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/commandline_parser/__init__.py", line 124, in parse_commandline_arguments
    if not any(selected_plugin.parse_commandline_arguments(arguments) for selected_plugin in selected_plugins):
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/commandline_parser/__init__.py", line 124, in <genexpr>
    if not any(selected_plugin.parse_commandline_arguments(arguments) for selected_plugin in selected_plugins):
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/plugins/__init__.py", line 27, in parse_commandline_arguments
    method()
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/plugins/builtins/devenv/__init__.py", line 216, in build
    self.create_setup_py()
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/plugins/builtins/devenv/__init__.py", line 104, in create_setup_py
    self.install_sections_by_recipe("infi.recipe.template.version")
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/plugins/builtins/devenv/__init__.py", line 90, in install_sections_by_recipe
    utils.execute_with_buildout("install {}".format(' '.join(sections_to_install)), stripped=stripped)
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/helper/utils/__init__.py", line 163, in execute_with_buildout
    execute_assert_success([buildout] + BUILDOUT_PARAMETERS + args, env=_env)
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/infi.projector-1.0.5-py3.5.egg/infi/projector/helper/utils/__init__.py", line 72, in execute_assert_success
    raise PrettyExecutionError(result)
infi.projector.helper.utils.PrettyExecutionError: Execution of ['bin/buildout', 'buildout:develop=', 'install', 'setup.py', '__version__.py'] failed!
result=1
stdout=Getting distribution for 'buildout.wheel'.
Got buildout.wheel 0.2.0.

stderr=warning: no files found matching 'shootout.cfg'
While:
  Installing.
  Loading extensions.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/zc.buildout-2.11.5-py3.5.egg/zc/buildout/buildout.py", line 2127, in main
    getattr(buildout, command)(args)
  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/zc.buildout-2.11.5-py3.5.egg/zc/buildout/buildout.py", line 638, in install
    self._load_extensions()
  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/zc.buildout-2.11.5-py3.5.egg/zc/buildout/buildout.py", line 1174, in _load_extensions
    ep.load()(self)
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/kalombo/.virtualenvs/infi/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kalombo/projects/infi.clickhouse_orm/eggs/buildout.wheel-0.2.0-py3.5.egg/buildout/wheel/__init__.py", line 9, in <module>
    import pip.pep425tags
ImportError: No module named 'pip.pep425tags'
```

Python 3.5.2, pip 10.0.1

**Comment by ishirav** [comment]
Are you sure you're pulled to the latest version on the develop branch?
My last commit addressed the error you're getting.
https://github.com/Infinidat/infi.clickhouse_orm/commit/50550ac6b65956b2730535c995565011af2dbe7a

**Comment by kalombos** [comment]
@ishirav my bad, it was not the latest version. Sorry. I updated my repository and all works fine now, issue can be closed.
