### ISSUE TITLE
1.0.0 breaks sqlalchemy-clickhouse

### ISSUE THREAD

**Issue by zyclonite** [Infinidat/infi.clickhouse_orm#76]
since the upgrade from 0.9.8 to 1.0.0 the following problem occurs

#### reproducer
```
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('clickhouse://127.0.0.1:8123')
conn = engine.connect()
result = pd.read_sql_query("SELECT * FROM test", conn)
conn.close()
```
#### exception
```
Traceback (most recent call last):
  File "query.py", line 6, in <module>
    result = pd.read_sql_query("SELECT * FROM test", conn)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/sql.py", line 332, in read_sql_query
    parse_dates=parse_dates, chunksize=chunksize)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/sql.py", line 1092, in read_query
    result = self.execute(*args)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/sql.py", line 983, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 209, in execute
    self._process_response(response)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 342, in _process_response
    cols = [(f[0], f[1].db_type) for f in r._fields]
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 342, in <listcomp>
    cols = [(f[0], f[1].db_type) for f in r._fields]
AttributeError: 'str' object has no attribute 'db_type'
```
#### versions used
* sqlalchemy-clickhouse 0.1.3.post0
* SQLAlchemy 1.2.2
* pandas 0.22.0
#### referenced issues
https://github.com/apache/incubator-superset/issues/5345

**Comment by haufau** [comment]
r._fields here is OrderedDict in 1.0.0, so generator here gets f as first element of row, Unicode object - column name
in 0.9.8 it is list of lists

**Comment by Manikandan25** [comment]
When connecting the superset with clickhouse, I faced a similar kind of issue that "Error:'str' object has no attribute 'db_type'.
Then, I downgraded my infi.clickhouse-orm package using the following command:
sudo pip install  infi.clickhouse-orm==0.9.8

Now, Its working fine.
Thank you,
Manikandan.K
