### ISSUE TITLE
infi.clickhouse_orm.database.ServerError: Memory limit for single record

### ISSUE THREAD

**Issue by vecchp** [Infinidat/infi.clickhouse_orm#77]
Hi I'm getting a Memory Limit exception when sending a single 1048576 byte record:

```Python
Traceback (most recent call last):
  File "extract.py", line 81, in <module>
    db.insert([tmpOrm])
  File "/usr/local/site-packages/infi/clickhouse_orm/database.py", line 180, in insert
    self._send(gen())
  File "/usr/local/site-packages/infi/clickhouse_orm/database.py", line 298, in _send
    raise ServerError(r.text)
infi.clickhouse_orm.database.ServerError: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 1048576 bytes), maximum: 9.31 GiB (241)
```

I'm unsure why it thinks my query would exceed 9.31GB even though the record itself is 48kB.  The clickhouse server also has no other users or queries in progress. Any thoughts?

**Comment by vecchp** [comment]
This may be an issue with a server side setting rather than an issue with the orm.  Will report back.

**Comment by ishirav** [comment]
@vecchp, did you manage to determine the source of this issue?
