### ISSUE TITLE
SystemPart QuerySet doesn't work

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#98]
Hi
```python
from infi.clickhouse_orm import SystemPart
bool(SystemPart.objects_in(db).filter(name='my_part'))
```
raises an exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 2, in <module>
  File "/home/vagrant/venv/lib/python3.6/site-packages/infi/clickhouse_orm/query.py", line 257, in __bool__
    return bool(self.count())
  File "/home/vagrant/venv/lib/python3.6/site-packages/infi/clickhouse_orm/query.py", line 325, in count
    return self._database.count(self._model_cls, self.conditions_as_sql())
  File "/home/vagrant/venv/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 219, in count
    r = self._send(query)
  File "/home/vagrant/venv/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 324, in _send
    raise ServerError(r.text)
infi.clickhouse_orm.database.ServerError: Table carrot_new.`system.parts` doesn't exist. (60)
```
Database name shouldn't be appended automatically for system models.

**Comment by ishirav** [comment]
Fixed on v1.1.0
